# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/appliedrec/verid3/serialization/common/face.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.appliedrec.verid3.serialization.common import pointf_pb2 as com_dot_appliedrec_dot_verid3_dot_serialization_dot_common_dot_pointf__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5com/appliedrec/verid3/serialization/common/face.proto\x12*com.appliedrec.verid3.serialization.common\x1a\x37\x63om/appliedrec/verid3/serialization/common/pointf.proto\"\x82\x04\n\x04\x46\x61\x63\x65\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\r\n\x05width\x18\x03 \x01(\x02\x12\x0e\n\x06height\x18\x04 \x01(\x02\x12\x0b\n\x03yaw\x18\x05 \x01(\x02\x12\r\n\x05pitch\x18\x06 \x01(\x02\x12\x0c\n\x04roll\x18\x07 \x01(\x02\x12\x0f\n\x07quality\x18\x08 \x01(\x02\x12\x45\n\tlandmarks\x18\t \x03(\x0b\x32\x32.com.appliedrec.verid3.serialization.common.PointF\x12\x44\n\x08left_eye\x18\n \x01(\x0b\x32\x32.com.appliedrec.verid3.serialization.common.PointF\x12\x45\n\tright_eye\x18\x0b \x01(\x0b\x32\x32.com.appliedrec.verid3.serialization.common.PointF\x12I\n\x08nose_tip\x18\x0c \x01(\x0b\x32\x32.com.appliedrec.verid3.serialization.common.PointFH\x00\x88\x01\x01\x12M\n\x0cmouth_centre\x18\r \x01(\x0b\x32\x32.com.appliedrec.verid3.serialization.common.PointFH\x01\x88\x01\x01\x42\x0b\n\t_nose_tipB\x0f\n\r_mouth_centreB\x03\xba\x02\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.appliedrec.verid3.serialization.common.face_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\272\002\000'
  _FACE._serialized_start=159
  _FACE._serialized_end=673
# @@protoc_insertion_point(module_scope)
