# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/appliedrec/verid3/serialization/capture3d/image_face_package.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.appliedrec.verid3.serialization.capture3d import image_3d_pb2 as com_dot_appliedrec_dot_verid3_dot_serialization_dot_capture3d_dot_image__3d__pb2
from com.appliedrec.verid3.serialization.common import face_pb2 as com_dot_appliedrec_dot_verid3_dot_serialization_dot_common_dot_face__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nFcom/appliedrec/verid3/serialization/capture3d/image_face_package.proto\x12-com.appliedrec.verid3.serialization.capture3d\x1a<com/appliedrec/verid3/serialization/capture3d/image_3d.proto\x1a\x35\x63om/appliedrec/verid3/serialization/common/face.proto\"\x99\x01\n\x10ImageFacePackage\x12\x45\n\x05image\x18\x01 \x01(\x0b\x32\x36.com.appliedrec.verid3.serialization.capture3d.Image3D\x12>\n\x04\x66\x61\x63\x65\x18\x02 \x01(\x0b\x32\x30.com.appliedrec.verid3.serialization.common.FaceB\x03\xba\x02\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.appliedrec.verid3.serialization.capture3d.image_face_package_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\272\002\000'
  _IMAGEFACEPACKAGE._serialized_start=239
  _IMAGEFACEPACKAGE._serialized_end=392
# @@protoc_insertion_point(module_scope)
