# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/appliedrec/verid3/serialization/capture3d/image_3d.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.appliedrec.verid3.serialization.capture3d import depth_map_pb2 as com_dot_appliedrec_dot_verid3_dot_serialization_dot_capture3d_dot_depth__map__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<com/appliedrec/verid3/serialization/capture3d/image_3d.proto\x12-com.appliedrec.verid3.serialization.capture3d\x1a=com/appliedrec/verid3/serialization/capture3d/depth_map.proto\"b\n\x07Image3D\x12\x0b\n\x03jxl\x18\x01 \x01(\x0c\x12J\n\tdepth_map\x18\x02 \x01(\x0b\x32\x37.com.appliedrec.verid3.serialization.capture3d.DepthMapB\x03\xba\x02\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.appliedrec.verid3.serialization.capture3d.image_3d_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\272\002\000'
  _IMAGE3D._serialized_start=174
  _IMAGE3D._serialized_end=272
# @@protoc_insertion_point(module_scope)
